---
title: "Assignment"
author: "Janek Teders"
date: "December 8, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE, cache = TRUE)
library(knitr)
library(readxl)
library(tidyverse)
set.seed(20190108)
```

# 1. Regarding the DBC

## 1.1 Load the DBC codes and its descriptions



### 1.2



# 2. Regarding NZa fees only
## 2.1 Extract the NZa fees



## 2.2 A methodology change in computing the NZa fees.
### 2.2a



### 2.2b 



## 2.3 Statistics and the Methodology for Computing the NZa Fees.
### The Programming Task



# 3. About the Insurances
## 3.1 Creating the Data Set



## 3.2 Joining the NZa fees, the Insurance fees and the DBC codes with descriptions



### 3.3 Visualizing the Reimbursements for Non-Contracted Healht Care 



## 3.4 About the Methodology of Average Contracted Fees



### 3.4a Average Contracted Fees



### 3.4b 



### 3.4c



## 3.5 Statistics on the % NZa fee reimbursed?



### 3.5a Boostrapped quantile intverals for VGZ and ZK?



### 3.5b Exploiting Symmetry $\theta$



# 4. A Small Monte-Carlo Study regarding symmetry about $\theta$



## 4.1 Type-I error



## 4.2 Power: More about symmetry about $\theta$



## 4.3 Reflecting on Permutation Tests.
### 4.3a



### 4.3b


